defmodule KiwiCodec.RustlerGenerator do
  @moduledoc """
  Generates Rustler decoder code from Kiwi schemas for RustQ manifests.

  This is an experimental bridge for optional native backends. It generates a
  complete Rust source file for schema-dependent decoder functions and NIF
  entrypoints; `rustq.exs` owns writing and freshness checks.

  The generated source includes the Rustler imports, RustQ Rustler term helpers,
  schema decoders, and requested entrypoints. The caller only needs to provide a
  `Decoder<'a>` type with Kiwi primitive reader methods.
  """

  alias KiwiCodec.RustlerGenerator.Name
  alias KiwiCodec.RustlerGenerator.Selection
  alias KiwiCodec.RustlerGenerator.Splice
  alias KiwiCodec.Schema
  alias KiwiCodec.Schema.Enum, as: SchemaEnum
  alias KiwiCodec.Schema.{Message, Struct}
  alias RustQ.Meta.AST, as: MetaAST
  alias RustQ.Rust
  alias RustQ.Rust.AST.Builder, as: A

  @primitive_decoders [
    {"bool", :read_bool, []},
    {"byte", :read_byte, []},
    {"float", :read_var_float, [:env]},
    {"int", :read_var_int, []},
    {"int64", :read_var_int64, []},
    {"string", :read_string, [:env]},
    {"uint", :read_var_uint, []},
    {"uint64", :read_var_uint64, []}
  ]

  for {type, method, args} <- @primitive_decoders do
    call =
      quote do
        decoder.unquote(method)(unquote_splicing(Enum.map(args, &Macro.var(&1, nil))))
      end

    defp primitive_decoder_expr(%{type: unquote(type)}) do
      unquote(Macro.escape(call))
    end
  end

  defp primitive_decoder_expr(_field), do: nil

  @type entrypoint :: {atom() | String.t(), String.t()}

  @doc """
  Returns a complete Rust source file for generated Rustler decoders.

      generate :native_decoders, "native/my_nif/src/generated.rs" do
        schema = KiwiCodec.parse_schema!(File.read!("priv/schema.kiwi"))

        content KiwiCodec.RustlerGenerator.source(schema,
          definitions: ["Node"],
          entrypoints: [decode_node: "Node"],
          module_prefix: "Example.Schema"
        )
      end

  Options:

    * `:definitions` - schema definition names to generate, including their
      dependencies. Defaults to all definitions.
    * `:entrypoints` - `{nif_name, definition_name}` entries for generated NIFs.
    * `:module_prefix` - Elixir module prefix for decoded structs.
    * `:decoder` - Rust path imported as `Decoder`. Defaults to
      `"crate::runtime::Decoder"`.

  """
  @spec source(Schema.t(), keyword()) :: String.t()
  def source(%Schema{} = schema, opts) do
    [source_header(opts), generated_fragments(schema, opts)]
    |> List.flatten()
    |> Enum.map_join("\n\n", &Rust.to_fragment/1)
    |> Kernel.<>("\n")
  end

  defp generated_fragments(%Schema{} = schema, opts) do
    definitions = Keyword.get(opts, :definitions, [])
    entrypoints = Keyword.get(opts, :entrypoints, [])
    module_prefix = Keyword.fetch!(opts, :module_prefix)

    definition_map = Selection.definition_map(schema)
    selected = Selection.definitions(schema, definitions, definition_map)

    [
      Splice.rustler_helpers(),
      definition_fragments(selected, module_prefix, definition_map),
      entrypoint_fragments(entrypoints)
    ]
  end

  defp source_header(opts) do
    decoder = Keyword.get(opts, :decoder, "crate::runtime::Decoder")

    """
    // This file is generated by KiwiCodec and RustQ. Do not edit by hand.
    #[allow(dead_code)]

    use rustler::types::atom::Atom;
    use rustler::{Binary, Encoder, Env, Error, NifResult, Term};
    use std::sync::OnceLock;

    use #{decoder};
    """
  end

  defp definition_fragments(definitions, module_prefix, definition_map) do
    definitions
    |> Enum.flat_map(&definition_items(&1, module_prefix, definition_map))
    |> Enum.map(&fragment_code/1)
  end

  defp definition_items(%SchemaEnum{} = definition, _module_prefix, _definition_map) do
    variant_statics =
      definition.variants
      |> Enum.with_index()
      |> Enum.map(fn {_field, index} ->
        atom_static(Name.enum_variant_atom_static(definition.name, index))
      end)

    variant_statics ++ [enum_decoder_item(definition)]
  end

  defp definition_items(%Struct{} = definition, module_prefix, definition_map) do
    [
      atom_static(Name.module_atom_static(definition.name)),
      keys_static(Name.struct_keys_static(definition.name)),
      struct_decoder_item(definition, module_prefix, definition_map)
    ]
  end

  defp definition_items(%Message{} = definition, module_prefix, definition_map) do
    [
      atom_static(Name.module_atom_static(definition.name)),
      keys_static(Name.struct_keys_static(definition.name)),
      message_decoder_item(definition, module_prefix, definition_map),
      message_fields_decoder_item(definition, module_prefix, definition_map)
    ]
  end

  defp atom_static(name) do
    Rust.ast_item(A.static(name, "OnceLock<Atom>", A.path_call([:OnceLock, :new])))
  end

  defp keys_static(name) do
    Rust.ast_item(
      A.static(name, "OnceLock<Vec<rustler::wrapper::NIF_TERM>>", A.path_call([:OnceLock, :new]))
    )
  end

  defp enum_decoder_item(%SchemaEnum{} = definition) do
    definition
    |> generated_enum_module!()
    |> MetaAST.item(Name.decoder_function(definition.name))
  end

  defp generated_enum_module!(%SchemaEnum{} = definition) do
    module =
      Module.concat([
        KiwiCodec.RustlerGenerator.Generated,
        "Enum#{definition.name}#{:erlang.phash2(definition)}"
      ])

    if Code.ensure_loaded?(module) do
      module
    else
      variants =
        definition.variants
        |> Enum.with_index()
        |> Enum.map(fn {field, index} ->
          {
            field.value,
            Name.static_alias(Name.enum_variant_atom_static(definition.name, index)),
            Name.field_name(field.name)
          }
        end)

      name = Name.decoder_function(definition.name)

      Module.create(
        module,
        quote do
          use RustQ.Meta
          alias RustQ.Type, as: R
          import KiwiCodec.RustlerGenerator.DecoderMacro, only: [enum_decoder: 2]

          enum_decoder(
            unquote(name),
            unquote(Macro.escape(variants))
          )
        end,
        Macro.Env.location(__ENV__)
      )

      module
    end
  end

  defp struct_decoder_item(%Struct{} = definition, module_prefix, definition_map) do
    definition
    |> generated_struct_module!(module_prefix, definition_map)
    |> MetaAST.item(Name.decoder_function(definition.name))
  end

  defp generated_struct_module!(%Struct{} = definition, module_prefix, definition_map) do
    module =
      Module.concat([
        KiwiCodec.RustlerGenerator.Generated,
        "Struct#{definition.name}#{:erlang.phash2({definition, module_prefix})}"
      ])

    if Code.ensure_loaded?(module) do
      module
    else
      name = Name.decoder_function(definition.name)
      field_exprs = Enum.map(definition.fields, &field_value_expr(&1, definition_map))

      Module.create(
        module,
        quote do
          use RustQ.Meta
          alias RustQ.Type, as: R
          import KiwiCodec.RustlerGenerator.DecoderMacro, only: [struct_decoder: 6]

          struct_decoder(
            unquote(name),
            unquote(Name.module_atom_static(definition.name)),
            unquote(Name.struct_keys_static(definition.name)),
            unquote(Name.module_name(module_prefix, definition.name)),
            unquote(Enum.map(definition.fields, &Name.field_name(&1.name))),
            unquote(Macro.escape(field_exprs))
          )
        end,
        Macro.Env.location(__ENV__)
      )

      module
    end
  end

  defp message_decoder_item(%Message{} = definition, module_prefix, definition_map) do
    definition
    |> generated_message_module!(module_prefix, definition_map)
    |> MetaAST.item(Name.decoder_function(definition.name))
  end

  defp message_fields_decoder_item(%Message{} = definition, module_prefix, definition_map) do
    definition
    |> generated_message_module!(module_prefix, definition_map)
    |> MetaAST.item(Name.message_fields_function(definition.name))
  end

  defp generated_message_module!(%Message{} = definition, module_prefix, definition_map) do
    module =
      Module.concat([
        KiwiCodec.RustlerGenerator.Generated,
        "Message#{definition.name}#{:erlang.phash2({definition, module_prefix})}"
      ])

    if Code.ensure_loaded?(module) do
      module
    else
      decoder_name = Name.decoder_function(definition.name)
      fields_name = Name.message_fields_function(definition.name)

      fields =
        definition.fields
        |> Enum.with_index()
        |> Enum.map(fn {field, index} ->
          {field.id, index + 1, field_value_expr(field, definition_map)}
        end)

      module_name = Name.module_name(module_prefix, definition.name)

      Module.create(
        module,
        quote do
          use RustQ.Meta
          alias RustQ.Type, as: R

          import KiwiCodec.RustlerGenerator.DecoderMacro,
            only: [message_decoder: 6, message_fields_decoder: 2]

          message_decoder(
            unquote(decoder_name),
            unquote(fields_name),
            unquote(Name.module_atom_static(definition.name)),
            unquote(Name.struct_keys_static(definition.name)),
            unquote(module_name),
            unquote(Enum.map(definition.fields, &Name.field_name(&1.name)))
          )

          message_fields_decoder(unquote(fields_name), unquote(Macro.escape(fields)))
        end,
        Macro.Env.location(__ENV__)
      )

      module
    end
  end

  defp field_value_expr(%{array?: true, type: "byte"}, _definition_map) do
    quote(do: decoder.read_byte_array(env))
  end

  defp field_value_expr(%{array?: true} = field, definition_map) do
    inner = field_result_expr(%{field | array?: false}, definition_map)

    quote do
      decoder.read_repeated(fn decoder -> unquote(inner) end)
    end
  end

  defp field_value_expr(field, definition_map), do: field_result_expr(field, definition_map)

  defp field_result_expr(field, definition_map) do
    primitive_decoder_expr(field) ||
      field
      |> referenced_definition!(definition_map)
      |> then(fn definition ->
        name = Name.decoder_function(definition.name)

        quote do
          unquote(name)(env, decoder)
        end
      end)
  end

  defp referenced_definition!(field, definition_map), do: Map.fetch!(definition_map, field.type)

  defp entrypoint_fragments(entrypoints) do
    Enum.map(entrypoints, fn {nif_name, definition_name} ->
      entrypoint_item(nif_name, definition_name)
    end)
  end

  defp entrypoint_item(nif_name, definition_name) do
    module = generated_entrypoint_module!(nif_name, definition_name)
    MetaAST.item(module, RustQ.Atom.identifier!(to_string(nif_name)))
  end

  defp generated_entrypoint_module!(nif_name, definition_name) do
    nif_name = RustQ.Atom.identifier!(to_string(nif_name))
    decoder_name = Name.decoder_function(definition_name)

    module =
      Module.concat([
        KiwiCodec.RustlerGenerator.Generated,
        "Entrypoint#{nif_name}#{:erlang.phash2(definition_name)}"
      ])

    if Code.ensure_loaded?(module) do
      module
    else
      Module.create(
        module,
        quote do
          use RustQ.Meta
          alias RustQ.Type, as: R
          import KiwiCodec.RustlerGenerator.DecoderMacro, only: [entrypoint: 2]

          entrypoint(unquote(nif_name), unquote(decoder_name))
        end,
        Macro.Env.location(__ENV__)
      )

      module
    end
  end

  defp fragment_code(fragment), do: RustQ.Rust.to_fragment(fragment)
end
